### ISSUE TITLE
Consider a more 'swifty' API

### ISSUE THREAD

**Issue by gmosx** [pointfreeco/swift-overture#2]
How about a more 'swifty' API, e.g.

```
pipe(incr, into: square) 
```

instead of

```
pipe(incr, square) 
```

**Comment by stephencelis** [comment]
Ha, we actually made `concat` a lil more "swifty" in order to support trailing closures.

``` swift
concat(buttonStyle) {
  $0.backgroundColor = .red
}

// vs.

concat(buttonStyle, and: {
  $0.backgroundColor = .red
})
```

This is a bit of a cheat code, but it works with `concat` as it scales to its variadic number of arguments.

``` swift
concat(a, b, c, d, e, f, and: g)
```

The `pipe` and `chain` functions also are overloaded to create larger pipelines. I'm not sure what to do about scaling them, though:

``` swift
pipe(a, into: b, then: c, before: d, andThen: e)
```

I'm also not sure if these kinds of labels are readable together. _E.g._, using `with` makes the meaning less clear:

```
with(x, pipe(incr, into: square))
```

I think in general the goal of these functions is to reduce visual noise and focus on the pipeline and composition. It should also be easy to manipulate existing pipelines and plug a new function into them anywhere, which is a flexibility that seems at odds with adding argument labels.

We're up to discuss ideas that address these problems, though!

**Comment by gmosx** [comment]
Heh, you got me confused. I am also not sure what is the best API after all ;-)

**Comment by jbarros35** [comment]
I'm using it just for say that's a huge achievement and work, I'm reading it and impress, do you had a Medium article about it?
That's a game change for Swift. I'm pretty sure that work will have recognition in the future when people would be aware of these workings.

**Comment by stephencelis** [comment]
Going to close this for now. Thanks for the discussion! Feel free to make suggestions for any other specific API changes by opening a new issue 😄
